<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <InvariantGlobalization>false</InvariantGlobalization>
    <SatelliteResourceLanguages>it;en</SatelliteResourceLanguages>
    <Version>0.1.0</Version>
    <Company>Punta e Ascolta</Company>
    <Product>Punta e Ascolta</Product>
    <NeutralLanguage>it-IT</NeutralLanguage>
  </PropertyGroup>
</Project>
