<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>PuntaEAscolta.Windows.Ocr</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PuntaEAscolta.Core\PuntaEAscolta.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
</Project>
